version: '2'
services:
    jhipsangularmonlith-app:
        image: jhipsangularmonlith
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsangularmonlith-mysql:3306/jhipsangularmonlith?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsangularmonlith-mysql:
        extends:
            file: mysql.yml
            service: jhipsangularmonlith-mysql
